### ISSUE TITLE
Make compatible with devtools dark theme

### ISSUE THREAD

**Issue by tophf** [kriserickson/lz-localstorage-chrome-extension#1]
Devtools theme may be set to `dark` in its Settings or via custom CSS theme, which makes this extension panel look bad because even lines don't have a background color.

* Ideal solution: find a way to detect current devtools theme darkness. Maybe by using getComputedStyle on `body`.
* Alternative solution: add a dark theme mode in your extension
* Simple solution: define a background color for the entire panel using e.g. `body`.

**Comment by kriserickson** [comment]
Get computed style returns transparent, and there is no easy way I can find to get the colour scheme for dark mode, so I have hard coded the background...  Looks like a few other dev-tools-extensions are doing this as well (I looked around trying to find the solution others were using).   Please re-open if you know of a good solution for getting colours from the theme.

**Comment by tophf** [comment]
Yay, [found it](https://crbug.com/608869):

```js
chrome.devtools.panels.themeName
```

**Comment by kriserickson** [comment]
@tophf  Fixed with commit 87435d2, version 0.2.1
